services:
  node_app:
    image: node
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: npx nodemon server.js
    depends_on:
      - mysql_db

  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
      #- ./httpd.conf:/usr/local/apache2/conf/httpd.conf

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"