#docker run -e EULA=TRUE -p 25565:25565 -v $HOME/world:/worlds/world:ro -e WORLD=/worlds/world itzg/minecraft-server
#./world is an unzip of the copied world
# it is copied to the empty dir of ./data/wolrd on first run
# probably not needed for continual use
# rcon-cli --host  localhost --password 14b3811a7dc96a0f1e9ea2a2
# remove rcon entry command if rcon is published out of the container 
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./world:/worlds/world
    environment:
      EULA: "TRUE"
      WORLD: /worlds/world
      # FORCE_WORLD_COPY: "true"
    user: "root:root" # probably not good, but fixes the file permision isue with player data